add example for pooling browsers
GoogleChromeLabs/puppeteer-examples pull request #14
Opened 2018-08-20 12:15 UTC by rahulkumar66

this is an example for pooling browsers resulting in faster load times of pages since we not don't have to open new browser for each request .
This results in improve load times especially in case of SPAs since cached resources can be reused.

2018-08-20 12:28 UTC, rahulkumar66 commented
I signed it.

2018-08-22 05:02 UTC, rahulkumar66 commented
This fixes #14

2018-08-22 18:43 UTC, ebidel requested changes
I think it might be interesting to have a flag that controls using a pool and not using a pool. And then throw in some `console.time` to show the difference in perf.

2018-08-22 18:43 UTC, ebidel commented on puppeteer-browser-pool.js
> +const VIEWPORT = { width: 1028, height: 800, deviceScaleFactor: 2 };
Sorry, we need linting.

- Can you remove the surrounding whitespaces after `{` and the first key name and the space before `}`.
- Use 2-space indentation everywhere.

2018-08-22 18:43 UTC, ebidel commented on puppeteer-browser-pool.js
> +        const browser = await puppeteer.launch(puppeteerArgs);
where does `puppeteerArgs` come from?

2018-08-22 18:43 UTC, ebidel commented on puppeteer-browser-pool.js
> +const factory = {
can we use a better name?

2018-08-22 18:43 UTC, ebidel commented on puppeteer-browser-pool.js
> +const HACKER_NEWS_QUERY_SPA_URL = 'https://hn.algolia.com/?query=angular';
let's use `https://hn.algolia.com/?query=chrome`

2018-08-22 18:43 UTC, ebidel commented on puppeteer-browser-pool.js
> +const HACKER_NEWS_QUERY_SPA_URL = 'https://hn.algolia.com/?query=angular';
This could also build off the base url.

2018-08-22 18:43 UTC, ebidel commented on puppeteer-browser-pool.js
> +        browser.close();
`return browser.close();`

2018-08-22 18:43 UTC, ebidel commented on puppeteer-browser-pool.js
> +})();
newline

2018-08-23 14:44 UTC, ebidel commented
Is it possible to add a few more examples to the demo that helps show why a pool is necessary in some cases. Otherwise it's easy just to use the same browser instance to open 2 tabs for the URLs you're using.

2018-08-24 05:40 UTC, rahulkumar66 commented
The reason we are parallelizing work through browsers and not pages is because one page crash might bring down the whole browser and also each page isn't guaranteed to be totally clean (cookies and storage might bleed-through as [seen here](https://bugs.chromium.org/p/chromium/issues/detail?id=754576)).

2018-08-24 13:34 UTC, ebidel commented
But that is unlikely :) The other one is a big in chrome that hopefully
gets fixed soon.

I'd prefer to encourage folks to use separate browser instances only when
it makes sense. It comes with much more overhead than launching a single
instance. Having a demo that shows when/why you'd need to go with many
instances would be more helpful IMO.

On Thu, Aug 23, 2018, 10:40 PM Rahul Kumar <notifications@github.com> wrote:

> The reason we are parallelizing work through browsers and not pages is
> because one page crash might bring down the whole browser and also each
> page isn't guaranteed to be totally clean (cookies and storage might
> bleed-through as seen here
> <https://bugs.chromium.org/p/chromium/issues/detail?id=754576>).
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleChromeLabs/puppeteer-examples/pull/14#issuecomment-415656846>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOigNgNRi0CBOgBxvKXxhW1e54Lpzaoks5uT5HQgaJpZM4WD4pV>
> .
>

2018-08-27 09:36 UTC, rahulkumar66 commented
i have used single browser in production and it was not stable over long periods of time maybe because i was using --single process flag.
Even [browserless.io](https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html) recommends running multiple browsers opposed to running multiple pages

2018-08-27 15:17 UTC, ebidel commented
I'm not arguing the benefits for certain use cases. I'm saying we should
have a demo that shows a case where you would want to do pooling.

On Mon, Aug 27, 2018, 2:36 AM Rahul Kumar <notifications@github.com> wrote:

> i have used single browser in production and it was not stable over long
> periods of time maybe because i was using --single process flag.
> Even browserless.io
> <https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html>
> recommends running multiple browsers opposed to running multiple pages
>

I'm confused because this is an argument against keeping a pool of long
running browsers open....

> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleChromeLabs/puppeteer-examples/pull/14#issuecomment-416172041>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOigJeh0Q54JCtldEvyBbZbs6FyvoDpks5uU72xgaJpZM4WD4pV>
> .
>

2018-09-04 05:48 UTC, rahulkumar66 commented
Ok i will add it

2019-11-04 14:14 UTC, SebastiyanKasurov commented on puppeteer-browser-pool.js
> +    return browser.close();
You receive page from (create), in destroy you receive browser

2022-06-14 18:52 UTC, rahulkumar666 commented on puppeteer-browser-pool.js
> +const factory = {
no

2025-12-12 11:58 UTC, closed without merging